/**
 * Measures real advance widths for the poster typeface and emits the table used
 * by lib/chart/text.ts.
 *
 * Advance width (not ink width) is what determines whether the next glyph
 * collides, and side bearings make ink width the wrong measurement. So for each
 * character we rasterise one copy and eleven copies, and take the difference
 * over ten — side bearings cancel out and what remains is the advance.
 *
 * Run after changing the poster typeface:
 *   npx tsx scripts/calibrate-widths.ts
 */

import { Resvg } from "@resvg/resvg-js";
import { resolve } from "node:path";

const FONT = resolve(process.cwd(), "assets/fonts/EBGaramond.ttf");
const SIZE = 200;
const REPEATS = 10;

const CHARS = [
  ..."abcdefghijklmnopqrstuvwxyz",
  ..."ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  ..."0123456789",
  " ", ".", ",", "'", "’", "-", "–", "(", ")", "&", "/",
  "á", "é", "í", "ó", "ú", "ä", "ö", "ü",
  "ñ", "ç", "å", "ø", "ł",
];

function inkWidth(text: string): number {
  const escaped = text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  const W = Math.ceil(SIZE * text.length * 1.2) + 400;
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${SIZE * 2}">` +
    `<rect width="${W}" height="${SIZE * 2}" fill="#fff"/>` +
    `<text x="100" y="${SIZE * 1.2}" font-family="EB Garamond" font-size="${SIZE}" ` +
    `fill="#000" xml:space="preserve">${escaped}</text></svg>`;

  const r = new Resvg(svg, {
    font: { fontFiles: [FONT], loadSystemFonts: false, defaultFontFamily: "EB Garamond" },
  });
  const img = r.render();
  const width = img.width;
  const height = img.height;
  const data = img.pixels as unknown as Buffer;

  let minX = Number.POSITIVE_INFINITY;
  let maxX = -1;
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const i = (y * width + x) * 4;
      const alpha = data[i + 3] ?? 0;
      const r0 = data[i] ?? 255;
      if (alpha > 10 && r0 < 200) {
        if (x < minX) minX = x;
        if (x > maxX) maxX = x;
      }
    }
  }
  if (maxX < 0) return 0;
  return maxX - minX + 1;
}

const table: Record<string, number> = {};

for (const ch of CHARS) {
  if (ch === " ") continue; // measured below via a bracketed run
  const one = inkWidth(ch);
  const many = inkWidth(ch.repeat(REPEATS + 1));
  const advance = (many - one) / REPEATS;
  table[ch] = Number((advance / SIZE).toFixed(4));
}

// Space has no ink, so measure it between two visible glyphs.
{
  const withSpaces = inkWidth("H" + " ".repeat(REPEATS) + "H");
  const without = inkWidth("HH");
  table[" "] = Number(((withSpaces - without) / REPEATS / SIZE).toFixed(4));
}

const values = Object.values(table).filter((v) => v > 0);
const mean = values.reduce((a, b) => a + b, 0) / values.length;

const entries = Object.entries(table)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([ch, w]) => {
    const key = /^[a-zA-Z]$/.test(ch) ? ch : JSON.stringify(ch);
    return `  ${key}: ${w},`;
  })
  .join("\n");

console.log(`// Generated by scripts/calibrate-widths.ts — do not edit by hand.
// Advance widths in em units, measured from ${FONT.split("/").pop()}.
export const DEFAULT_W = ${mean.toFixed(4)};
export const W: Record<string, number> = {
${entries}
};`);
